### ISSUE TITLE
Hexo+Github Pages写博客

### ISSUE THREAD

**Issue by Jimmy2Angel** [Jimmy2Angel/Blog#1]
小白想写点东西记录一下自己学习的道路，在网上看到用[Hexo](https://hexo.io/) + [Github Pages](https://pages.github.com/)的居多，折腾了大概一天，终于搭起来了。以下为本次折腾的内容==。

###	Git和NodeJS
这个没什么好说的，网上下载下来安装就ok

## github pages相关
登录github，创建一个名为username.github.com的repository

### 安装

执行下面这个命令下载hexo
```
npm install -g hexo-cli
```
cd到一个目录下执行下面这个命令进行初始化
```
hexo init
```
安装hexo的扩展插件
```
npm install
```
生成静态页面
```
hexo g
```
开启本地服务器
```
hexo s
```
访问https://localhost:4000 就可以看到效果了，如果一直在加载可能是端口号4000被占用了，可以用下面这个命令开启本地服务器
```
hexo s -p 4001
```

### 使用
上面只是在本地上访问的，下面需要部署到github上
首先需要修改_config.yml文件最后三行为
```
deploy:
     type: git
     repo: https://github.com/Jimmy2Angel/Jimmy2Angel.github.com.git
     branch: master
```
然后使用下面的命令发布到github上
```
hexo generate 
hexo deploy
```
然后访问https://jimmy2angel.github.io/ 就可以看到hexo默认的HelloWorld了

### 新建一篇文章
```
hexo new "my first blog"
```
在source/_posts文件夹下生成一个my-first-blog.md文件，用markdown编辑器编辑好后，按上面所说发布到github上即可。在某些情况下需要在执行generate命令
```
hexo g
```
前先执行一个clean命令
```
hexo clean
```
然后在执行deploy命令
```
hexo d
```
